oliexdev/openScale

android_app/app/src/main/java/com/health/openscale/core/EvaluationSheet.java
android_app/app/src/main/java/com/health/openscale/core/ScaleCalculator.java
android_app/app/src/main/java/com/health/openscale/core/ScaleUser.java
android_app/app/src/main/java/com/health/openscale/gui/Measurement.java
android_app/app/src/main/java/com/health/openscale/gui/OverviewFragment.java
android_app/app/src/main/java/com/health/openscale/gui/ScaleDiff.java

Hi MilenaMMay,
I would like to merge your good code refactoring contributions back to the master branch.
Greetings from Germany
Oli

OpenScale code refactoring contributions

---

.gitignore
android_app/android_app.iml
android_app/app/app.iml
android_app/app/build.gradle
android_app/app/src/main/AndroidManifest.xml
android_app/app/src/main/java/com/health/openscale/gui/ReminderBootReceiver.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/ReminderPreferences.java
android_app/app/src/main/res/values-de/strings.xml
android_app/app/src/main/res/values/strings.xml
android_app/app/src/main/res/values/type_weekdays.xml
android_app/app/src/main/res/xml/reminder_preferences.xml
android_app/build.gradle
android_app/gradle/wrapper/gradle-wrapper.properties

Hi,
I imported the project into Android Studio to test Issue #5. In an emulator the alarms are triggered, as long the app isn't removed from the recent apps list. We'll have to see how this works on a real device.
I did some small refactorings in the refactorings in the reminder code. I'm not use if you really want to integrate this one, because I also changed some *iml* files :-/
But maybe you can take a look pick the parts you like.
Best regards
wolkenschieber

Interationalize weekday names, Update libraries, some constants

---

README.md

This PR adds a button with a link to F-Droid and change the one for Google Play Store
Thanks for this app

Update for the README

---

android_app/app/src/main/java/com/health/openscale/gui/OverviewFragment.java
android_app/app/src/main/res/values-fr/strings.xml

french tranlation + BMI  text adaptation in overview for other languages

added french translation

---

android_app/app/app.iml
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/SettingsActivity.java

When you modify settings, the fragment are now refreshed when you press "Back".

Gui changes

---

android_app/app/app.iml
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/SettingsActivity.java

Nastynabz gui changes

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSbf70.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/res/values/type_btdevices.xml

Support for:
- weight
- fat
- water
- muscle
No history support.

Add support for Sanitas SBF-70 scale

---

android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
android_app/app/src/main/res/layout/fragment_graph.xml

Graphics: reverse top chart and bottom chart. This way, from top to bottom, char are years->months->days instead of years->days->months.
It makes it also clearer that you can press on the months' graphs to change the days' graph.

Graphics: reverse top chart and bottom chart

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSbf70.java

Sanitas SBF-70: The fat percentage appears to be in big endianness instead of little endianness

Sanitas SBF-70: Fix fat percentage

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java

Add another HW address for Medisana Smartscale

Add new HW address for Medisana BS444; MagicNumber is current time, fixes wrong timestamp;

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java

added another hardware address for issue described in #54

added HW address of my bs444

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java

add hwAddress DB2FF6 for Medisana BS 444 Connect

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSbf70.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/res/values/strings.xml

This PR contains a couple of enhancements.
The major ones are
* the enhanced SBF 70 support.
* sequential message handling for Bluetooth LE 
Most of the features of the SBF 70 are supported now,
especially:
* creating users with baseline measurements
* reading of user specific history data
* couple of bugfixes of parsing the correct data
* correct data/time handling
If there are any questions, let me know.

Better Sanitas SBF 70 support

---

android_app/app/src/main/res/values-pl/strings.xml

Create strings.xml for Polish language

---

android_app/app/src/main/res/values-sk/strings.xml

Updated translation

---

android_app/app/src/main/res/values-sk/strings.xml

Fixed some mismatches in slovak translation

Updated slovak translation

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMGB.java

Mgb scales

---

README.md

Makes it possible to click the badge and get to travis directly.

Point build status badge to travis

---

.travis.yml
android_app/app/build.gradle
android_app/build.gradle
android_app/gradle/wrapper/gradle-wrapper.properties
android_app/upload_apk.sh

As suggested by Android Studio 3.0.1.

Upgrade gradle and use default build tools version

---

android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
android_app/app/src/main/java/com/health/openscale/gui/views/BMIMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/BMRMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/BoneMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/CommentMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/FatMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/HipMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/LBWMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/LinearGaugeView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MuscleMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/WHRMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/WHtRMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/WaistMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/WaterMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/WeightMeasurementView.java

By drawing the value text under the linear gauge it doesn't collide with the limit text and is easier to read. Also made the min and max value dynamic to put the normal zone in the middle and give a better resolution for the values that the user cares about.
Also some centering of text and minor fixes.

Make the linear gauge easier to read

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/alarm/AlarmHandler.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCustomOpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothDigooDGSO38H.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMGB.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS444.java
android_app/app/src/main/java/com/health/openscale/core/bodymetric/EstimatedFatMetric.java
android_app/app/src/main/java/com/health/openscale/core/bodymetric/EstimatedWaterMetric.java
android_app/app/src/main/java/com/health/openscale/core/database/ScaleDatabase.java
android_app/app/src/main/java/com/health/openscale/core/database/ScaleUserDatabase.java
android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleData.java
android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleUser.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
android_app/app/src/main/java/com/health/openscale/gui/activities/UserSettingsActivity.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/FragmentUpdateListener.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/StatisticsFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BackupPreferences.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/UsersPreferences.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/res/drawable/rect_normal.xml
android_app/app/src/main/res/values-pl/strings.xml

Converted tabs to four spaces, removed trailing whitespace and some other whitespace cleanups. Use `git diff -w master..` to see the changes without the whitespace changes.

Whitespace cleanup

---

android_app/app/src/main/res/values-es/strings.xml

Added spanish language

---

android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementViewUpdateListener.java

If e.g. the weight is changed, also update the BMI value.
Also some minor bug fixes to not show evaluator row when there is no value to evaluate, and to make it possible to click the evaluator row to hide it.

Update diff value and dependent values when measurement change

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF700.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF800.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java

see https://github.com/oliexdev/openScale/issues/111

openscale support of Beurer BF700 & BF800

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF700_800.java

Confirmed to be the same as the Beurer BF800

Added Runtastic Libra

---

strings_dutch.xml

strings_dutch.xml

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiMini.java

Hi I tested with Yunmai Mini 2/Yunmai Balance and its also works. I also attach the pictures, please let me know if you need anything else.

Add support for Yunmai Mini 2/Yunmai balance

---

CREDITS
android_app/app/build.gradle
android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bodymetric/EstimatedFatMetric.java
android_app/app/src/main/java/com/health/openscale/core/bodymetric/EstimatedLBWMetric.java
android_app/app/src/main/java/com/health/openscale/core/bodymetric/EstimatedWaterMetric.java
android_app/app/src/main/java/com/health/openscale/core/evaluation/EvaluationResult.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/FragmentUpdateListener.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementViewUpdateListener.java
android_app/app/src/main/res/values/strings.xml

Show a custom activity when a crash happens, enabling the user to copy the stacktrace to the clipboard and points him/her to github for reporting issues.

Stacktrace

---

android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/StatisticsFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
android_app/app/src/main/java/com/health/openscale/gui/views/LinearGaugeView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/res/drawable/flat_selector.xml
android_app/app/src/main/res/drawable/rect_disabled.xml
android_app/app/src/main/res/drawable/rect_normal.xml
android_app/app/src/main/res/layout/fragment_statistics.xml
android_app/app/src/main/res/values/colors.xml

Fixes a few minor issues that I've come across. Please see individual commits for more info.

Some more misc changes

---

android_app/app/schemas/com.health.openscale.core.database.AppDatabase/2.json
android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleUser.java

Removing the annotations requires adding a database migration as the scheme changes.

Readd NonNull annotation on ScaleUser gender and scaleUnit

---

android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java

A few bug fixes/improvements after the data entry rewrite.

Data entry misc

---

android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/res/values/strings.xml

This fixes the last part of #81 (and #164) (together with #198).

Add next button to input dialog for moving directly to next measurement

---

android_app/app/src/main/java/com/health/openscale/gui/preferences/MeasurementPreferences.java

Also don't call getContext() directly as that requries newer API version.
Fixes a crash after my last PR. Don't know how I could miss that...

Add missing listener unregister

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/StatisticsFragment.java
android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java

I think this fixes the memory leak. At least there is only one instance of MainActivity and fragments after screen rotation (as seen in the profiler once the GC has run).

Fix memory leak

---

android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java

A minor cleanup. After this I'm hopefully done with the export thingy ;)

Release old persistable permission when new export is done

---

android_app/app/src/main/java/com/health/openscale/gui/views/CommentMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/FloatMeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
android_app/app/src/main/res/layout/float_input_view.xml
android_app/app/src/main/res/values-ca/strings.xml
android_app/app/src/main/res/values-cs/strings.xml
android_app/app/src/main/res/values-de/strings.xml
android_app/app/src/main/res/values-es/strings.xml
android_app/app/src/main/res/values-fr/strings.xml
android_app/app/src/main/res/values-ja/strings.xml
android_app/app/src/main/res/values-nl/strings.xml
android_app/app/src/main/res/values-pl/strings.xml
android_app/app/src/main/res/values-pt/strings.xml
android_app/app/src/main/res/values-sk/strings.xml
android_app/app/src/main/res/values-sv/strings.xml
android_app/app/src/main/res/values-tr/strings.xml
android_app/app/src/main/res/values/strings.xml

* Add inc and dec buttons to the dialog for quickly doing small
adjustments in the same way as in activity.
* Improve "next" measurement behavior by not recreating the whole
dialog and instead update the icon, title, view and buttons.

Improve measurement input dialog

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothIhealthHS3.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothPreferences.java

Basic scale support - weight only ,which is all the scale supports, now working for me.
Attached it picture of the scale

iHealth HS3 scale

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java

Fixed #218 (at least I think so).

Handle invalid user being selected in config

---

android_app/app/src/main/res/values-pl/strings.xml

Added missing strings with their translations. Some minor corrections.

 Updated translation

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java

dont send user data again if scale got it
save weight only after 2500ms or if all data completed

much better BT connection

---

README.md
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS44x.java

Hi! I had reversed BS430 protocol in order to check if it works the same way as BS440. My investigations show that it's definitely true, however time offset is not required. I'd like to contribute this PR .

Add Medisana BS430 to list of supported scales

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java

changed saving issue if scale does only scan weigth and then shut down

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java
android_app/app/src/main/java/com/health/openscale/core/utils/Converters.java

Support for mazon.com/Bluetooth-FITINDEX-Wireless-Bathroom-Composition/dp/B078HW8BPY FitIndex -
QNScale as provided by https://github.com/srwareham/openScale/blob/feature_qn_scale/android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java

FitIndex -  QNScale

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCustomOpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothDebug.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothDigooDGSO38H.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExcelvanCF36xBLE.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExingtechY1.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothHesley.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothIhealthHS3.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothInlife.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMGB.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS44x.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOneByone.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothTrisaBodyAnalyze.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothPreferences.java
android_app/app/src/main/java/com/health/openscale/gui/views/ChartMeasurementView.java

simplified Bluetooth machine state

Bluetooth state machine 2.0

---

android_app/app/src/main/java/com/health/openscale/gui/views/ChartMeasurementView.java

fix average array size in order to allocate 0...(maxXValue-minXValue)
and convert to 0-origin index from binNR(is a value of range minXValue <=> maxXValue).

fix average array size and index

---

android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/gui/views/ChartMeasurementView.java

Run toast message on UI thread

---

android_app/app/build.gradle
android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java

Sanitas SBF70/SBF75 (GATT_INSUF_AUTHORIZATION) bug fix

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java

See https://github.com/oliexdev/openScale/issues/451#issuecomment-488489720

Fix Senssun gender byte, remove unnecessary casts

---

.travis.yml
android_app/app/build.gradle
android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCustomOpenScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothDebug.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothDigooDGSO38H.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExcelvanCF36xBLE.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExingtechY1.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothGattUuid.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothHesley.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothInlife.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMGB.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS44x.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOneByone.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothStandardWeightProfile.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothTrisaBodyAnalyze.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothPreferences.java
android_app/build.gradle
android_app/gradle/wrapper/gradle-wrapper.properties

replaced RxAndroidBle with [Blessesd-Android](https://github.com/weliem/blessed-android)

Replaced Bluetooth backend to Blessed android library

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/YunmaiLib.java

resistance value should apply `sqrt` when that value is greater than 200

Apply missing part of the YunmaiLib.getFat logic

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/YunmaiLib.java

- LBM: scale machine just use `weight - fat` formula
- vis fat: function value range is 1 to 30, if openScale want to diff range value, we should rearrange it. also original app applied `floor` calculation to return value. but I didn't apply it.

Add YUNMAI LBM & visceral fat value.

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/YunmaiLib.java

this patch needs to confirm from newer version users and fix the muscle value of
normal body users
a getMuscle function doesn't be related `sex`, only related `body_type`
in the original app, if body_type is 1(fitness body type), it should multiply
with 0.7.
if not (normal body type), it should multiply with 0.67

Support activity level in Yunmai scales

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java

I have a Vigorun and it's named `YG` so here's a simple PR to add support for that :)

add Vigorun YG

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOneByone.java

- fix for issue #548: support for 1byOne model CF398BLE while maintaining compatibility with old 20-byte measurements
- set clock and download and delete history of 1byOne scales

fix for issue #548: support for 1byOne model CF398BLE

---

android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleMeasurement.java

Fix caliper body fat value by not calculating if not all values are set

---

android_app/app/src/main/java/com/health/openscale/gui/measurement/BMIMeasurementView.java

BMI over 50 is not unlikely, raise the value to something extreme.
BMI 125 would be about 300kg at 1.55m body height.

Significantly raise BMI MaxValue

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/OneByoneLib.java

Adjust the value of bodyVar instead of replacing bodyVar with the adjustment factor.

Fix bodyfat calculation for 1byone

---

README.md
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF105.java
fastlane/metadata/android/en-GB/full_description.txt
fastlane/metadata/openScale_pro/en-GB/full_description.txt

only adding scale in documentation and in scale type for connection

Added information for supported scale BF720

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothHuaweiAH100.java

It could connect to device, write user info and current time/date. Could read measurement (online, standing on the scale). In theory it should read offline measurements too, but not working on my scale.
In scale datasheet is mentioned that offline measurement will not work if two device are bound to same scale. Maybe it is the reason, why I cannot get offline measurements (scale do not recognize which user measurement apply to)

Init commit of AH100 / CH100.

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOKOK.java

Support for additional OKOK/Chipsea-BLE based scale

Support for additional OKOK/Chipsea-BLE based scale

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java

Hello, could you add please the Sanitas SBF73 , it is the same as SBF72 #940

Add Sanitas SBF73 ( same as SBF72)

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOKOK2.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothPreferences.java
android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothSettingsFragment.java

Support for nameless OKOK scales (Myria MY4836)

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java

[Healthsense S1](https://healthsense.in/products/healthsense-s1-luxury-smart-bluetooth-body-weighing-scale) is a smart Bluetooth weighing scale sold in India and manufactured by [ICOMON](https://fitdays.cn/).
Issue #1094

Add Healthsense S1 (AAA013)

---

android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java
android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java

Add support for Crane Bluetooth Scale
https://github.com/oliexdev/openScale/issues/315

Add Crane Bluetooth Scale
