- android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
Graphs: Ignore 0 values. They are meaningless and just indicate a lack of data.
They also force the graph Y axis to go down to 0.
Signed-off-by: Jerome Flesch <jflesch@kwain.net>
> Graphs: Ignore 0 values

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSbf70.java
- History downloading is not supported with the Sanitas SBF-70
- Sanitas SBF-70: Add BT address prefix reported by @nykroy
> History downloading is not supported with the Sanitas SBF-70 + new address prefix

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
Notes:
- This is basically a copy of BluetoothMiScale.java with some data offset adjustments
- The old realtime measurement characteristic is absent
- We only get impedance measurements, no direct body fat calculation is done on the firmware
- ~~The scale is not yet switched to kg, it is still operated in catty and there is no HW switch!~~ **DONE**
> Initial working support for Mi Scale v2

- android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
- android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleData.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/UserSettingsActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/TimePreferenceDialog.java
- android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
- android_app/app/src/main/res/layout/activity_usersettings.xml
* Present date in the "medium" (default) format (e.g. Nov 9, 2017)
instead of dd.MM.YYYY (e.g. 09.11.2017). Besides that it is easier
to read and wraps better in the table view, it is also localized and
avoids the uncertainty if day or month comes first.
* Similar, time is now presented in a localized format (i.e. 12 or 24
hour clock is taken from system settings).
* The time pickers are also configured to show a 12 or 24 hour clock
depending on the system setting.
* Handling of birthday and goal date is now fully done in the user
settings activity and OpenScale.(add|update)ScaleUser no longer has
to know which format the date string was in.
* The date and time measurement view now opens the date/time picker
with the initial date/time set to the measurement's value.
> Unify date and time handling

- .travis.yml
- android_app/app/build.gradle
- android_app/app/src/main/java/com/health/openscale/core/utils/DateTimeHelpers.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/StatisticsFragment.java
- android_app/app/src/main/res/values-de/strings.xml
- android_app/app/src/main/res/values-es/strings.xml
- android_app/app/src/main/res/values-fr/strings.xml
- android_app/app/src/main/res/values-ja/strings.xml
- android_app/app/src/main/res/values-pl/strings.xml
- android_app/app/src/main/res/values-pt/strings.xml
- android_app/app/src/main/res/values-sk/strings.xml
- android_app/app/src/main/res/values-sv/strings.xml
- android_app/app/src/main/res/values-tr/strings.xml
- android_app/app/src/main/res/values/strings.xml
- android_app/app/src/test/java/com/health/openscale/core/utils/DateTimeHelpersTest.java
I find it more logical to see how long ago a measurement was done,
instead of how long ago since the last measurement was a measurement
done.
Fix a bug where the days since a measurement was calculated
incorrectly if the measurement was done in the previous year.
Convert the days label to plurals so that "day" is used when the
measurement was done yesterday.
> Show days since current date in overview

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSbf70.java
- android_app/app/src/main/res/values-ca/strings.xml
1) SanitasSBF70 was saving the date-time at which data was recovered  by the app and tnot the date-time of the measurement. Solved.
2) Catalan/Valencian translation included.
> SanitasSBF70 problem with time. Catalan/Valencian language added.

- android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
- android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleMeasurement.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BMIMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BMRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BoneMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/CommentMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/FatMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/FloatMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/HipMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/LBWMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MuscleMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WHRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WHtRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WaistMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WaterMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WeightMeasurementView.java
The biggest part of this PR involves refactoring the inheritance hierarchy for MeasurementViews by adding a new FloatMeasurementView that all measurement views that holds a float inherits from. This way the base class MeasurementView can be cleaned up as much code is moved to FloatMeasurementView where it can deal with the value in a more explicit way as it is always float there.
The second part of this involves changing the DataEntryActivity to not save measurements to the database when navigating between them unless they have been modified. This improves the performance when switching between measurements. I have some more things I would like to do in this area, such as changing how the active user is handled, but that is for later.
DataEntryActivity now holds on to a clone of the …
> Refactor measurement views

- android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
- android_app/app/src/main/java/com/health/openscale/core/utils/CsvHelper.java
- android_app/app/src/main/java/com/health/openscale/junit/CsvHelperTest.java
- android_app/app/src/main/java/com/health/openscale/junit/DateTimeHelpersTest.java
Add support for importing CSV exports done with all versions back to version 1.0. Also fixed a bug where the user id wasn't set before inserting imports in database.
> Support importing old CSV exports

- android_app/app/build.gradle
- android_app/app/src/androidTest/java/com.health.openscale/DatabaseTest.java
- android_app/app/src/test/java/com.health.openscale/CsvHelperTest.java
- android_app/app/src/test/java/com.health.openscale/DateTimeHelpersTest.java
I was trying to add another android test but I couldn't figure out how to actually run it. But after moving the test to androidTest it was really simple to run from android studio.
I also looked at the build log from Travis and as far as I can tell the unit tests aren't running there as no test sources could be found. By moving them to where gradle expects them the tests are now run.
I know you didn't want the tests here, but it makes it much simpler to actually run them so I hope you can accept it.
> Move test to the location where gradle expects to find them

- android_app/app/build.gradle
Fixes some of the build problems I've been having when rebuilding tests and saves about 1.5MB when comparing app-debug.apk between master and this branch.
> Update dependency type to match what the dependency is used for

- android_app/app/schemas/com.health.openscale.core.database.AppDatabase/2.json
- android_app/app/src/androidTest/java/com/health/openscale/DatabaseMigrationTest.java
- android_app/app/src/androidTest/java/com/health/openscale/DatabaseTest.java
- android_app/app/src/androidTest/java/com/health/openscale/gui/ScreenshotRecorder.java
- android_app/app/src/main/java/com/health/openscale/core/OpenScale.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExingtechY1.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiMini.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE.java
- android_app/app/src/main/java/com/health/openscale/core/database/AppDatabase.java
- android_app/app/src/main/java/com/health/openscale/core/database/ScaleDatabase.java
- android_app/app/src/main/java/com/health/openscale/core/database/ScaleUserDatabase.java
- android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleMeasurement.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/UserSettingsActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/BackupPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/MeasurementPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/UsersPreferences.java
Changes the constraint for datetime to also include userId so that two users can have measurement for the same time. Also added a foreign key constraint so that there must be an user to be able to add a measurement. Added migration + test to verify that the upgrade works.
Tested import of a backup database with version 1. To have the migration steps run after import I changed the code to reopen the database after the import is done.
Also introduced caching of the selected scale user so that it doesn't have to be read from the database all the time.
Also some cleanups, such as the removal of unused methods from the old database classes.
> Database upgrade and cleanup

- android_app/app/src/main/java/com/health/openscale/core/utils/CsvHelper.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/views/CommentMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/FloatMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
Make data entry activity and graph and table fragment remember the state so that when the user e.g. rotates the screen, the state isn't lost.
Also made switching year in graph view move from e.g. January 2018 to December 2017 instead of to January 2017.
> Activity state

- android_app/app/schemas/com.health.openscale.core.database.AppDatabase/2.json
- android_app/app/src/main/java/com/health/openscale/core/database/AppDatabase.java
- android_app/app/src/main/java/com/health/openscale/core/datatypes/ScaleMeasurement.java
By putting userId first we avoid a compiler warnings an most likely
make better use of the index.
> Change order of columns in index

- .travis.yml
8d7f573f83 made the app_name untranslatable which broke the regex.
> Fix dev name setting

- android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
Also, don't allow search for bluetooth scale if no user is selected.
Fixes #192 and potentially also #158.
> Don't start data entry activity if no user is selected

- android_app/app/src/androidTest/java/com/health/openscale/DatabaseMigrationTest.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothExingtechY1.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
- android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/SettingsActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/GraphFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/OverviewFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/fragments/TableFragment.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/GeneralPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/MeasurementPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/UsersPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
- android_app/app/src/main/res/values-cs/strings.xml
- android_app/app/src/main/res/values-de/strings.xml
- android_app/app/src/main/res/values-es/strings.xml
- android_app/app/src/main/res/values-sv/strings.xml
- android_app/app/src/main/res/values/strings.xml
Recreate activity after settings have changed. This makes both the app theme take effect immediately and updates measurement views correctly after adding/removing measurements.
Add option so that date/time is once again placed last on the data entry activity. The views don't jump around as much then when switching between edit/view. 
Some other minor changes/improvements.
> Measurements

- android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/activities/DataEntryActivity.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/MeasurementPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BMIMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BMRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/BoneMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/CommentMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/DateMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/FatMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/FloatMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/HipMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/LBWMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/MuscleMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/TimeMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WHRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WHtRMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WaistMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WaterMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/views/WeightMeasurementView.java
- android_app/app/src/main/res/values/strings.xml
- android_app/app/src/main/res/xml/measurement_preferences.xml
By long pressing a view in the data entry activity, the view can be dragged up or down to change the order. The order is then saved and reflected in overview, graph, table and data entry fragments/activity.
This fixes part of #81 (and #164).
> Make it possible to change order of measurment views

- android_app/app/src/main/java/com/health/openscale/gui/MainActivity.java
Fixes crash when trying to export to a files that has been removed.
> Verify that it's possible to get filename from old export

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
Appears to be a clone of the MGB scale with a different device name and appearance
Image:
> Add support for Easy Home (Aldi) 64050

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMGB.java
Use user preferences to set correct unit.
Lbs is currently hardcoded.
Tested with Easy Home 64050 (support added #258) which appears to be a clone of the MGB scale.
Probably worth testing with the original MGB scale, but works fine with the Easy Home unit
> Sets scale unit during initialisation

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMedisanaBS44x.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothTrisaBodyAnalyze.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/TrisaBodyAnalyzeLib.java
- android_app/app/src/main/java/com/health/openscale/core/utils/Converters.java
- android_app/app/src/test/java/com/health/openscale/ConvertersTest.java
- android_app/app/src/test/java/com/health/openscale/TrisaBodyAnalyzeLibTest.java
This pull request covers two changes:
1. I added calculation of body composition data for the Trisa Body Analyzer scale, based on logic from the reverse-engineered Trisa Vital Bluetooth app. The reliability of these figures is questionable, but it's better than nothing.
2. I expanded Converters.java, adding support for decoding signed integers, and encoding to an existing byte array. Using these functions in the Trisa Body Analyze driver allowed me to remove some of the custom encoding/decoding logic there.
> Improve BluetoothTrisaBodyAnalyze

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
My Runtastic/Adidas Libra shows as "Libra-W", and was marked as non-supported in openScale. I tried using this tiny patch and everything is working great now!
> Added support for Libra-W

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java
Fixes #428. The magic number sent to initiate weight readings contains a byte describing which units the scale should be set to. The previous implementation hard coded this as 0x01 for KG. This PR switches the unit (either LB or KG) to be based on the value retrieved by `OpenScale.getInstance().getSelectedScaleUser().getScaleUnit()`
Please note that my ability to build the apk is currently down and I am unable to test this (although the code is extremely simple, I don't think it should be a problem). Hoping Travis will accomplish this.
> Fix force QN-Scale to KG

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
Since Yunmai Mini 2 China version uses bluetooth name "YUNMAI-ISM2T", the current matching rules does not work. This patch makes it work.
> Support Yunmai Mini 2 China version

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
Added additional BT identifier/name for Medisana BS444 model (currently unrecognized in openScale Pro app), not entirely sure whether the current code works, please check.
> Additional Medisana BS444 BT Identifier

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/YunmaiLib.java
1. this device name is just `YUNMAI-SIGNAL`
2. a packet sample is `0D 13 12 02 00 5D DD 67 22 00 00 AB A5 1C 00 00 EA 3E`;
only contains resistance value without fat.
I try to reverse `getFat` funtion of the `libconfig.so`
but return value could be little different.
> Support old Yunmai premium 1

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java
I was having an issue with a SENSSUN scale and the openScale app where the app would only write a new record about 20% of the time. 
The scale seemed to ignore the user synchronization message and the app would sit waiting for the measurement data (fat/water...) which never arrived. 
This change resends the userSynchronisation message to the scale (after stabilization) until it responds with the other metrics. 
This change has my scale responding correctly without fail since I changed the code.
> Update to SENSSUN scale Bluetooth code

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothStandardWeightProfile.java
`%i` is not a valid format specifier in Java and if this code is executed creates an exception. Use `%d` instead.
Signed-off-by: Peter Huewe <peterhuewe@gmx.de>
> Replace %i format specifier with %d

- android_app/app/src/main/java/com/health/openscale/gui/preferences/ReminderPreferences.java
The reminder day preference summary was listing the days out of order, and also always using the english text of the values. I've also removed the square brackets around the list, I thought it made it look a bit like debug output.
Before:
After:
> Reminder day preference fix

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothHoffenBBS8107.java
In this PR I added a support for Hoffen smart smart scale available in Poland: [User Guide PL/EN](https://hoffen.com.pl/wp-content/uploads/2018/02/WAGA-%C5%81AZIENKOWA-9-W-1-Z-FUNKCJ%C4%84-ANALIZY_BBS-8545.pdf) (it seems currently in sale is newer model BBS-8545, but both looks the same). Fortunately, the protocol was quite simple because scale itself doesn't seem to store any data.
> Add support for Hoffen BBS-8107 bathroom scale

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOKOK.java
For now only handles weight, impedance is read, but not used for
anything, algorithms not known.
The scale does not indicate whether it is sending the weight in kg or in
lbs, always assuming kg.
Based on findings from #496
> Add support for chipsea / OKOK 2.0 scales

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerSanitas.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothCommunication.java
The SBF70 has three bad habits:
- It sends the scale status reply multiple times (three, as it seems).
- When the user is standing on the scale, measurement are sent out unrequested.
- In both situations the scale ignores other commands.
Previously, the BeurerSanitas state machine was not robust against those effects:
- When it received messages that didn't not match the current state, it sometimes still advanced to the next state. This caused missing information and undefined behavior in later steps.
- When it sent out a request while the scale was busy with something other, the request got lost, the state machine never received the required answer and it got stuck in a state.
- When a measurement message was received before the user list was compiled, a null dereference cause an …
> SBF70: Make BeurerSanitas state machine more robust

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOneByone.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/OneByoneLib.java
Previously, the value reported for muscle mass was lean body mass
less skeletal mass. This was not a correct report for muscle mass
since it included additional values, such as organs and skin mass.
In addition, the impedance value previously used was incorrect.
There were, in fact, two different calculations being performed
for impedance based on data fields that were not relevant to it,
therefore the value for impedance was entirely incorrect, jumpy,
and unpredictable. In fact, the correct bytes for impedance are
the second and third bytes in the data packet received from the
scale, which produces correct and reasonable impedance values.
This commit corrects the prior errors, provides a calculation for
lean body mass, and calculates muscle mass based on the Janssen
formula; …
> Update calculations for OneByone scales

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF105.java
The BF105 reports the body water in kg while the app (and the scale) displays body water as percentage.
This pull request converts the received value so that it is displayed correctly.
As I was unsure if this issue also applies to the other Beurer scales that inherit from the BluetoothStandardWeightProfile I put the fix into the BF105 specific class.
> Save body water as percentage instead of kg on BF105

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSenssun.java
This PR aims to fix the excessive toast messages when taking measurements with a Senssun scale.
With these changes, the app will show only one toast when the weight has stabilized instead of 20 or more toast messages like right now.
> Fix Senssun excessive toasts

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSinocare.java
This PR adds support for the Sinocare [CW266 Digital bluetooth bathroom scale](https://en.sinocare.com/products/sinocare-digital-bathroom-scales-weighing-scale-high-precision-sensors-bluetooth-health-analyzer-with-smart-app-body-weight-scale).
This scale appears to be similar in operation to the scale added in #706 with regard to the contents of [this](https://github.com/oliexdev/openScale/pull/706#issuecomment-790393142) comment which basically says the scale only uses the manufacturer data field to broadcast data using bluetooth's Advertising mechanism and does not offer a proper service for accessing these values. The same is true for this scale and I suspect the reason for this is that this sinocare scale has a rather short timeout of about 10 seconds before it turns off, making it …
> Support Sinocare CW286 bluetooth bathroom scales

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
The support of Silvercrest SBF76 is the same as for Beurer BF105, BF600, BF850, BF950 and Silvercrest SBF77 (see https://github.com/oliexdev/openScale/pull/753). I just had to insert the deviceName and everything works. I tested the following functions:
- After resetting the scale I could successfully connect via Bluetooth (PIN exchange)
- The Users were also created (only the first letter is shown in the scale display)
- There is support for auto detecting a user. 
- All sensor values are transmitted and synced (weight, water, muscle, fat, bones)
- Multiple users are also supported and synced successfully
The following issue and pull request indicate also that the protocol should be the same overall the devices:
- https://github.com/oliexdev/openScale/pull/753
- …
> Support for Silvercrest SBF76 (Same as Beurer BF105, BF600, BF850, BF950 and Silvercrest SBF77)

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothSanitasSBF72.java
The Beurer BF915 seems to work just like the Sanitas SBF72. I just had to add a constructor parameter for the device name.
I have successfully tested the following functions:
- Connection and initial setup
- Using users who have already been created on the scale (with pin confirmation)
- Data transmission (including history data)
- User auto detection
> Support for Beurer BF915 (based on Sanitas SBF72).

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothMiScale2.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/lib/MiScaleLib.java
- android_app/app/src/main/java/com/health/openscale/core/evaluation/EvaluationSheet.java
- android_app/app/src/main/java/com/health/openscale/gui/measurement/LBMMeasurementView.java
Fixes #787 .
Rather than changing the muscle value, we can fill the lean mass value which was already implemented, in such a way we do not contradict what is being shown in the mifit app.
This PR adds some reference values for lean mass from a [pubmed paper]( https://pubmed.ncbi.nlm.nih.gov/30536335/) too.
> Miscale2 lean mass fix

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYoda1Scale.java
Yoda1 is a simple scale which broadcasts its measurements through advertising packets, with the name "Yoda1". It's LE only and not connectable. Some resellers say that the device can measure body impedance, but from my experience it only has a fake, fixed value equals to 0x1388.
I copied some code from `BluetoothOKOK`.
> Add support for Yoda1

- android_app/app/src/main/java/com/health/openscale/gui/measurement/ChartMeasurementView.java
I don't really know how to properly fix this, but experimentally I have found the value of the offset multiplier which fixes the issue of labels being cut out. It eats a little bit more space when no decimal places are present, but at least it works fine otherwise. I understand that this is a dirty hack, so no hard feelings from my side if it doesn't make it upstream.
Screenshot before:
Screenshots after:
> Increase the offset so that Y-axis labels with decimals places fit

- android_app/app/build.gradle
- android_app/app/src/main/java/com/health/openscale/gui/measurement/ChartMeasurementView.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/GraphPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/utils/TrendlineComputationMethod.java
- android_app/app/src/main/res/values/arrays.xml
- android_app/app/src/main/res/values/strings.xml
- android_app/app/src/main/res/xml/graph_preferences.xml
This code adds a simple moving average trend line with an option to select the time period over which the line should be averaged.
It is different from the currently implemented exponential smoothing because the simple moving average does not account for the old measurements: even though the old measurements are supposed to contribute little, they still contribute, and therefore the current state of things isn't represented properly (at least for me).
There are no future predictions in this implementation, only the moving average.
Also, my simple moving average should work properly with irregular measurements, while the current implementation of the exponential smoothing works incorrectly when there are long periods without data since it works measurement-wise, not time-wise. I.e., if I …
> Simple moving average on the chart

- android_app/app/src/main/java/com/health/openscale/gui/table/StickyHeaderTableView.java
This PR handle the case where some text ends by an `\n` (ex: 'something\n'). From `String.split` docs, ` trailing empty strings will be discarded.`. That cause the exception since there are less element than expected in the resulting array. 
From this screenshot, you can see the bug in action.
Thanks for the app oliexdev :)
Fix #935
> (fix) StickyHeaderTableView: crash on certain strings

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothYunmaiSE_Mini.java
This fixes issue #926 at least for the Yunmai scales.
300 ms delay added to step 0 of the bluetooth connection.
> Fix for Yunmai scales

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothActiveEraBF06.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
PR contains rudimentary support for Active Era BS-06 scales.
Scales report weight, feet balance (weight distribution), raw impedance readout from the ADC, and heart rate.
All of those are logged, but only weight is reported in the app. 
Historical measurements are also parsed, but not stored.
The BIA is done inside a native library, which I haven't looked at yet.
> Support for Active Era BS-06 scales

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothOKOK2.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothPreferences.java
- android_app/app/src/main/java/com/health/openscale/gui/preferences/BluetoothSettingsFragment.java
Reopen PR https://github.com/oliexdev/openScale/pull/1081
> ReOpen PR Support for nameless OKOK scales (Myria MY4836)

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothBeurerBF500.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
Beurer's BF500 seems to be a mix of BF105 and BF600. Characteristics determined by using BLE Scanner and trial & error. I did not verify that `CHARACTERISTIC_BEURER_BF500_SCALE_SETTING` and `CHARACTERISTIC_BEURER_BF500_REFER_WEIGHT_BF` are correct or do what they are supposed to do as they were not implemented by other scales.
What works:
- Transferring a user from the app to the scale (e.g. deleting all users on the scale before connecting with the app)
- Taking measurements (Weight, BMI, Body water, Body fat)
- Body Water required the same calculations as with BF105 before working correctly, the rest was correct out-of-the-box
What doesn't work:
- I've set up a user with my correct birth year (1988), but on the scale the user was created with birth year 1995 - day and month were correct …
> Initial support for Beurer BF500

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothESCS20M.java
- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothFactory.java
This pr adds support for the Renpho ES-CS20M scale with the firmware version v1.
The scale only sends the impedance, but when I use the 'YunmaiLib' to calculate the body composition data, I get similar results to the original app.
The scale does support historical data, but it is sent via the same characteristic as the normal measurements. This, and the fact that I couldn't find a date in the data, meant that I couldn't add support for historical data. To avoid messing up the measurements, the historical data is removed from the scale at the beginning (hint for the wiki?).
> Add support for Renpho ES-CS20M

- android_app/app/src/main/java/com/health/openscale/core/bluetooth/BluetoothQNScale.java
- I'm not able to test how this affects anyone with the older/currently working scales
> Adds compatibility with Renpho (QN Scale) scales that use the 2nd set of characteristics
